services:
  keycloak:
    image: quay.io/keycloak/keycloak:24.0
    container_name: keycloak_notes
    environment:
      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 7080
      KC_HOSTNAME_STRICT_BACKCHANNEL: "true"
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HEALTH_ENABLED: "true"
      KC_LOG_LEVEL: info
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7080/health/ready"]
      interval: 15s
      timeout: 2s
      retries: 15
    command: ["start-dev", "--http-port", "7080", "--https-port", "7443"]
    ports:
      - "7080:7080"
      - "7443:7443"
    networks:
      - local_network
    volumes:
      - .var/keycloak:/opt/keycloak/data
  postgres:
    image: postgres:latest
    container_name: postgres_notes
    volumes:
      - .var/postgresql:/var/lib/postgresql/data
      - ./config/create-db.sql:/docker-entrypoint-initdb.d/create_database.sql
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - local_network
  sonic:
    image: valeriansaliou/sonic:v1.4.9
    container_name: sonic_notes
    ports:
      - "1491:1491"
    volumes:
      - ./config/sonic.cfg:/etc/sonic.cfg
      - .var/sonic:/var/lib/sonic/store

networks:
  local_network:
    driver: bridge